### ISSUE TITLE
Function not found when linking two components together

### ISSUE THREAD

**Issue by Officeyutong** [bytecodealliance/wasmtime#5785]
I have two wasm components `gcd2.wasm` and `gcd4.wasm`. 
- The first one implements and exports a function `gcd2: func(a: s64, b: s64) -> s64` which calculates the greatest common divisor of two integers. 
- The second one imports the `gcd2` function, whose signature is the same as described above, and exports a function `gcd4: func(a: s64, b: s64, c: s64, d: s64) -> s64`, which uses the imported `gcd2` function to calculate the greatest common divisor of four integers (i.e `gcd(a,b,c,d)=gcd(gcd(gcd(a,b),c),d)`).  

I'm using `wasmtime::component` to load the two components, link them together, and invoke the `gcd4` function, but `Linker::instantiate` returned an error, indicating that `gcd2` is not defined.

My code is here:

```rust
use wasmtime::{
    component::{Component, Linker},
    Store,
};
struct MyState {}
fn main() {
    let mut config = wasmtime::Config::new();
    config.wasm_component_model(true);
    let engine = wasmtime::Engine::new(&config).unwrap();

    let gcd2 = Component::from_file(&engine, "gcd2.wasm").unwrap();
    let gcd4 = Component::from_file(&engine, "gcd4.wasm").unwrap();
    
    let mut store = Store::new(&engine, MyState {});
    let linker = Linker::new(&engine);
    // linker.instance("ss").unwrap().
    linker.instantiate(&mut store, &gcd2).unwrap();
    linker.instantiate(&mut store, &gcd4).unwrap();
}
```

### Test Case

The two wasm components are in the following zip file:

[linker-demo.zip](https://github.com/bytecodealliance/wasmtime/files/10743862/linker-demo.zip)

### Steps to Reproduce

- Create a new rust project using `cargo new`
- Modify `main.rs` like mentioned above
- Put the two wasm component files in the root directory of the project
- `cargo run`
### Expected Results

No panics happened

### Actual Results

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: import `gcd2` has the 
wrong type

Caused by:
    expected func found nothing', src\main.rs:18:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Versions and Environment

Wasmtime version or commit: rev `255fd6b`, with feature `component-model`

Operating system: `Windows 10, 21H1 19044.2486` 

Architecture: x64

### Extra Info
Cargo.toml:
```toml
[package]
name = "linker-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", rev = "255fd6b", features = ["component-model"] }
```
